### PR TITLE
Passing the correct env variable.

### PR DESCRIPTION
**Pull request by Exulansis**
Change to the value checked for in the `config.js` file.

### CODE REVIEW

**Review by craigmulligan — APPROVED** [review]

**Review by craigmulligan — CHANGES_REQUESTED** [review]
Currently I pass the NODE_ENV flag when running the container, so this should actually be added to the `environment` config in agile-stack. 

That's why the ci tests are failing - because if NODE_ENV=test runs the test suite.

**Comment by Exulansis** [comment]
So this PR can be closed, and a new PR needs to be opened on Agile Stack?
Or just add them to the the agile-ui integration branch for agile stack.

**Comment by Exulansis** [comment]
So per your comment @craig-mulligan, something like this:
```
agile-data:
  container_name: agile-data
  ...
  environment:
    - NODE_ENV = production
```
 in the docker-compose.yml file should suffice, correct?
I've tested this locally and it does solve the issue.

**Comment by craigmulligan** [comment]
Yes exactly 👍

**Comment by Exulansis** [comment]
Thank you, closing.

**Pull request closed without merging**
